# server configuration
server:
  port: 9192

# endpoint configuration
endpoints:
  shutdown:
    enabled: true

# database configuration
spring:
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: none

  datasource:
    url: jdbc:mariadb://database-server:3306/stellar_connector
    username: root
    password: skdcnwauicn2ucnaecasdsajdnizucawencascdca
    driver-class-name: org.mariadb.jdbc.Driver

# stellar horizon server configuration
stellar:
  horizon-address: https://horizon.fintechsys.net
  installation-account-private-key: GC3H6AEDE56Q3TRQG3HXQ4K6PNZD2YWKA63T6X74ZW4V7XTTHKO3TQFJSAWGKNJJ4O5YLITG34JBRLP55VEVQ7QNAPWXS3AFFO7QHLYQG7K5ZYHW
  local-federation-domain: 
  new-account-initial-balance: 10000
